### PR TITLE
feat: Update & Delete Plugin Options

### PR DESCRIPTION
**Pull request by Pheon-Dev**
```
$ zap update
$ zap delete
$ zap pause
$ zap unpause
$ zap -h
```
Zap Version Option Still to Come
Picture_4

### CODE REVIEW

**Comment by ChristianChiarulli** [comment]
can we put the plug or charger emoji or icon there instead of the folder?

image

or 

🔌

**Comment by Pheon-Dev** [comment]
I'm using exa, it's just running ls in the plugins folder

**Comment by Pheon-Dev** [comment]
If there's a fancier way to list all plugins it would be great😁

**Comment by Rishabh672003** [comment]
i am using this pr and it works great

**Pull request merged**
